# Generated by Django 5.1.1 on 2024-11-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_bot_message_next_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_button',
            name='btn_type',
            field=models.CharField(choices=[('Inline', 'Inline'), ('Reply', 'Reply')], default='Inline', help_text='Тип кнопки', max_length=128),
        ),
        
        migrations.AddField(
            model_name='bot_message',
            name='anyway_link',
            field=models.CharField(blank=True, help_text='На какое состояние пебрасывает пользователя', max_length=110, null=True, unique=True),
        ),

        migrations.AddField(
            model_name='botuser',
            name='days_in_project',
            field=models.PositiveIntegerField(default=0, verbose_name='Дней в проекте'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='has_mentor',
            field=models.BooleanField(default=False, verbose_name='Есть ли наставник'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='login',
            field=models.CharField(default=0, max_length=100, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='payment_wallet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кошелёк для выплат'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='project_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент в проекте'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='service_display_enabled',
            field=models.BooleanField(default=True, verbose_name='Отображение сервиса залета'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='status',
            field=models.CharField(default='', max_length=100, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='today_profit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма профитов за сегодня (USD)'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='today_profit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Сегодняшнее количество профитов'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_profit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Общая сумма профитов (USD)'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_profit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество профитов'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='user_id',
            field=models.BigIntegerField(default=0, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='bot_message',
            name='handler',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя функции обработчика'),
        ),
    ]
