# Generated by Django 5.1.1 on 2024-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_bot_button_btn_type_bot_message_anyway_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='has_mentor',
            field=models.CharField(default='', verbose_name='Есть ли наставник'),
        ),
    ]
