# Generated by Django 5.1.1 on 2024-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_botuser_has_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='has_mentor',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Есть ли наставник'),
        ),
    ]
