# Generated by Django 5.1.1 on 2024-11-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_botuser_has_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='days_in_project',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Дней в проекте'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='login',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='project_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент в проекте'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='today_profit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма профитов за сегодня (USD)'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='today_profit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сегодняшнее количество профитов'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='total_profit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Общая сумма профитов (USD)'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='total_profit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Общее количество профитов'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID пользователя'),
        ),
    ]
