# Generated by Django 5.1.1 on 2024-11-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_botuser_days_in_project_alter_botuser_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='login',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='service_display_enabled',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='botuser',
            name='tokensmartsupp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tokensmartsupp'),
        ),
    ]
