# Generated by Django 5.1.1 on 2024-11-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_mentors_username_alter_mentors_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='has_mentor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Есть ли наставник'),
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, help_text='Стоимость', null=True)),
                ('data', models.DateField(blank=True, help_text='Дата получения', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Стоимость', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_user', to='bot.botuser')),
            ],
        ),
    ]
