# Generated by Django 5.1.1 on 2024-11-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_botuser_activate_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, help_text='id объявления', max_length=255, null=True)),
                ('name', models.TextField(blank=True, help_text='Нвазние товара', null=True)),
                ('price', models.FloatField(blank=True, help_text='Цена товара', null=True)),
            ],
            options={
                'verbose_name': 'Ссылку',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
