# Generated by Django 5.1.1 on 2024-11-21 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_user', to='bot.botuser'),
        ),
    ]
