# Generated by Django 5.1.1 on 2024-11-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_links_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='days_in_project',
        ),
    ]
