# Generated by Django 5.1.1 on 2024-11-22 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_remove_botuser_days_in_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='data_register',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дней в проекте'),
        ),
    ]
