# Generated by Django 5.1.1 on 2024-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_botuser_data_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='project_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Процент в проекте'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='today_profit_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Сегодняшнее количество профитов'),
        ),
    ]
