# Generated by Django 5.1.1 on 2024-11-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_alter_botuser_project_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='today_profit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма профитов за сегодня (USD)'),
        ),
    ]
