# Generated by Django 5.1.1 on 2024-11-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_alter_botuser_today_profit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='service',
            field=models.CharField(blank=True, help_text='Название сервиса', max_length=255, null=True),
        ),
    ]
