# Generated by Django 5.1.1 on 2024-11-22 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_country_country_sites_alter_links_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country_sites',
            options={'verbose_name': 'Сайты стран', 'verbose_name_plural': 'Сайты стран'},
        ),
        migrations.AddField(
            model_name='country_sites',
            name='name_country',
            field=models.ForeignKey(blank=True, help_text='К какой стране привязка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_sites', to='bot.country'),
        ),
    ]
