# Generated by Django 5.1.1 on 2024-11-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_alter_country_sites_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, help_text='Уникальный токен для идентификации.', max_length=255, null=True)),
                ('url', models.URLField(blank=True, help_text='Ссылка', null=True)),
                ('price', models.CharField(blank=True, help_text='Цена (в формате 0.00).', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, help_text='Изображение', null=True, upload_to='products/')),
                ('name', models.CharField(blank=True, help_text='Имя продавца', max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='Адрес доставки', null=True)),
            ],
            options={
                'verbose_name': 'Данные пользовательской страницы',
                'verbose_name_plural': 'Данные пользовательской страницы',
            },
        ),
    ]
