# Generated by Django 5.1.1 on 2024-12-02 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0032_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='datausersite',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
