# Generated by Django 5.1.1 on 2024-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0033_datausersite_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='datausersite',
            name='data_json',
            field=models.JSONField(blank=True, help_text='json', null=True),
        ),
    ]
