# Generated by Django 5.1.1 on 2024-12-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0034_datausersite_data_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='token_temporary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Временный токен для передачи'),
        ),
    ]
