# Generated by Django 5.1.1 on 2024-12-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0036_datausersite_support_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('target_port', models.IntegerField(default=8091)),
            ],
        ),
    ]
