# Generated by Django 5.1.1 on 2024-12-05 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0038_rename_domain_domain_name_remove_domain_target_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
