# Generated by Django 5.1.1 on 2024-12-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_alter_domain_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.AddField(
            model_name='country_sites',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
