# Generated by Django 5.1.1 on 2024-12-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0040_delete_domain_country_sites_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_sites',
            name='url',
            field=models.CharField(blank=True, help_text='Введите URL-адрес', max_length=555, null=True),
        ),
    ]
